export const INCREMENT_COUNTER = 'App/INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'App/DECREMENT_COUNTER';

export const LOGIN_USER_PENDING = 'App/LOGIN_USER_PENDING';
export const LOGIN_USER_SUCCESS = 'App/LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'App/LOGIN_USER_ERROR';

export const LOGOUT_USER = 'App/LOGOUT_USER';
export const FORM_RESET = 'redux-form/RESET';

export const INIT_LUNCHDARKLY_PENDING = 'APP/INIT_LUNCHDARKLY_PENDING';
export const INIT_LUNCHDARKLY_SUCCESS = 'APP/INIT_LUNCHDARKLY_SUCCESS';
export const INIT_LUNCHDARKLY_ERROR = 'APP/INIT_LUNCHDARKLY_ERROR';
export const TOGGLE_COUNTER_BUTTON = 'counter-button';

export const FEATURE_TOGGLED = 'FEATURE_TOGGLED';

