export const INCREMENT_COUNTER = 'App/INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'App/DECREMENT_COUNTER';

export const LOGIN_USER_PENDING = 'App/LOGIN_USER_PENDING';
export const LOGIN_USER_SUCCESS = 'App/LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'App/LOGIN_USER_ERROR';

export const LOGOUT_USER = 'App/LOGOUT_USER';
export const FORM_RESET = 'redux-form/RESET';

export const INIT_OPTIMIZELY_PERNDING = 'APP/INIT_OPTIMIZELY_PERNDING';
export const INIT_OPTIMIZELY_SUCCESS = 'APP/INIT_OPTIMIZELY_SUCCESS';
export const INIT_OPTIMIZELY_ERROR = 'APP/INIT_OPTIMIZELY_ERROR';

export const FEATURE_TOGGLED = 'APP/FEATURE_TOGGLED';

export const TOGGLE_COUNTER_BUTTON = 'counter-button';

